# Generated by Django 5.2.8 on 2026-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
