# Generated by Django 5.2.8 on 2025-12-27 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagoryName', models.CharField(max_length=100)),
                ('catagoryDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField(default=django.utils.timezone.localdate)),
                ('eventTime', models.TimeField(default=django.utils.timezone.now)),
                ('eventLocation', models.TextField(max_length=100)),
                ('eventImage', models.ImageField(blank=True, default='events_photo/defaultevent.png', null=True, upload_to='events_photo')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_catagory', to='events.catagory')),
                ('participants', models.ManyToManyField(related_name='rsvp_events', to='users.participant')),
            ],
        ),
    ]
