# Generated by Django 5.2.7 on 2025-10-23 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default=datetime.date(2025, 10, 23)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventTime',
            field=models.TimeField(default=datetime.time(17, 24, 11, 743629)),
        ),
    ]
